name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter=1.0.0
  - seaborn=0.11.2
  - pandas=1.4.4
  - pip=22.1.2
  - pyarrow=8.0.0
  - pip:
      - wandb==0.16.3
      - ydata_profiling==4.6.4